### ISSUE TITLE
Ninject DI with SignalR in AspNetCore

### ISSUE THREAD

**Issue by toondedo** [lord-executor/Ninject.Web.AspNetCore#10]
Hi, I have been trying out `Ninject.Web.AspNetCore` in combination with `Microsoft.AspNetCore.SignalR` to handle websockets and I've stumbled upon an issue which I haven't been able to figure out yet.

#### SignalR hubs
SignalR works by adding `SignalR.Hub`s to your server project. These hubs allow you to call methods on connected clients. The currently connected clients to each hub is managed by SignalR via a context object for each type of hub. Inside the scope of a hub, you have access to the matching context so you are able to send messages to the connected clients.
#### SignalR hubs context
It is also possible to communicate with connected clients outside of said hubs by injecting the context of a hub in a component of your choosing. This is achieved by requesting `IHubContext<THub>` from the DI container.
#### SignalR strongly typed hubs
The downside of using the regular `IHubContext` is that it relies on magic strings. To overcome this, SignalR provides a base class for strongly typed hubs: `public abstract class Hub<T> : Microsoft.AspNetCore.SignalR.Hub where T : class`. 
Using this in combination with an interface, the hub (and also the context) become strongly typed.
Requesting typed hubs from from the DI container is done by requesting `IHubContext<THub, T>`.
This is the part where I'm experiencing difficulties to achieve with Ninject.

Retrieving `IHubContext<THub>` instances works out of the box but I've been unsuccessful in requesting a `IHubContext<THub, T>` instance.

#### Hub setup
```cs
public interface IHubTest
{
    Task Push();
}

public class HubTest : Hub<IHubTest>
{
}
```
#### Application (Program.cs)
```cs
var kernel = new AspNetCoreKernel(new NinjectSettings { LoadExtensions = false }, new AspNetCoreModule());
var builder = WebApplication.CreateBuilder(args);
builder.Host.UseServiceProviderFactory(new NinjectServiceProviderFactory(kernel));
builder.Services.AddSignalR();

var app = builder.Build();
app.UseEndpoints(endpoints =>
{
    endpoints.MapHub<HubTest>("/test");
});
app.RunAsync();
```
#### Retrieving hub context
Right after the `app.RunAsync()`:
```cs
// The following statement provides to correct IHubContext
var simpleContext = kernel.Get<IHubContext<HubTest>>();
```
However
```cs
// The following statement throws Ninject.ActivationException: "No matching bindings are available, and the type is not self-bindable."
var typedContext = kernel.Get<IHubContext<HubTest, IHubTest>>();
```
By removing `builder.Host.UseServiceProviderFactory(new NinjectServiceProviderFactory(kernel));` (so using the default AspNetCore DI), the context is successfully retrieved:
```cs
// var typedContext = kernel.Get<IHubContext<HubTest, IHubTest>>();
var typedContext = app.Services.GetService<IHubContext<HubTest, IHubTest>>();
```

### What I've tried so far
When adding the `IHubContext<THub, T>` to the `builder.Services` in any `ServiceLifeTime`, the `Ninject.ActivationException` is changed to "No constructor was available to create an instance of the implementation type."
```cs
builder.Services.AddTransient<IHubContext<HubTest, IHubTest>>();
```
Or explicitly binding in Ninject does give an instance of the context but it seems to give a copy of a singleton so no clients are connected to the resolved context:
```cs
kernel.Bind<IHubContext<HubTest, IHubTest>>()
    .ToMethod(ctx => builder.Services.BuildServiceProvider().GetService<IHubContext<HubTest, IHubTest>>());
```
for which the IDE already gives a warning [by this diagnostics](https://docs.microsoft.com/en-us/aspnet/core/diagnostics/asp0000?view=aspnetcore-6.0).
Explicit binding in Ninject to `app.Services.GetService<IHubContext<HubTest, IHubTest>>()` puts Ninject in a binding loop (or at least that is what I suspect is happening).

### The question
I'm in the dark on how to set this up properly.
Am I missing something trivial or could I get a pointer to any direction on where the problem might be?

Is it possible to setup Ninject to also use the default DI instead of completely replacing it? Can the SignalR items be resolved via the default container through Ninject?

Please do request extra information if not all is clear.
Thanks in advance.

### Resources:
SignalR hub: https://docs.microsoft.com/en-us/aspnet/core/signalr/hubs?view=aspnetcore-6.0
SignalR stronly typed hubs: https://docs.microsoft.com/en-us/aspnet/core/signalr/hubs?view=aspnetcore-6.0#strongly-typed-hubs
SignalR hub context injection: https://docs.microsoft.com/en-us/aspnet/core/signalr/hubcontext?view=aspnetcore-6.0#inject-a-strongly-typed-hubcontext
I used the Blazor example to setup my `Program.cs`: https://github.com/lord-executor/Ninject.Web.AspNetCore/blob/main/src/SampleBlazorApplication/Program.cs
### Used nuget packages and version
Ninject.Web.AspNetCore: 6.0.0
Microsoft.AspNetCore.SignalR: 1.1.0

**Comment by elca-lan** [comment]
Well... that took a while. Sorry about that 😬.

I'm writing to let you know that I am currently looking into that issue. I **can** reproduce it and as of right now it doesn't make a lot of sense to me since open generic bindings should work just fine and pretty much the same for a single and _two_ open generic types.

A "Ninject-only" example with a _similar_ setup of interfaces and implementations seems to work just fine
```
kernel.Bind(typeof(IFoo<>)).To(typeof(TheFoo<>)).InSingletonScope();
kernel.Bind(typeof(IFoo<,>)).To(typeof(TheFoo<,>)).InSingletonScope();

kernel.Get<IFoo<Exception>>();
kernel.Get<IFoo<Exception, IEnumerable>>();
```

**Comment by toondedo** [comment]
Cool, thanks for taking a look at it! Glad you found the cause.

Out of curiosity, I've tried what you mentioned and I think I can confirm:
- a "Ninject-only" setup does work as expected
- when skipping the filtering on the available bindings in `ConstrainedGenericBindingResolver`, the request could successfully resolve

A solution to the problem would be nice so I can clean up my current workaround but there is no pressure 👍 
I have already looked at it as well but that's been unsuccessful so far.

**Comment by lord-executor** [comment]
I've already got a solution now. Just working on cleaning it up a bit and adding your scenario to my sample project in addition to the tests that I have already added.

It was really just a bit of a stupid implementation of the `ConstrainedGenericBindingResolver` that backfired on me. The constrained generic binding resolver is required to be compliant with Microsoft.Extensions.DependencyInjection which allows multiple services to be registered for the same interface (with open generics) which is substantially differnt from what Ninject normally does.

If you're interested, the relevant "compliance" tests can be found in Microsofts dotnet/runtime repo under
* [DependencyInjectionSpecificationTests.cs](https://github.com/dotnet/runtime/blob/v6.0.7/src/libraries/Microsoft.Extensions.DependencyInjection.Specification.Tests/src/DependencyInjectionSpecificationTests.cs)
  * ConstrainedOpenGenericServicesCanBeResolved
  * AbstractClassConstrainedOpenGenericServicesCanBeResolved
  * OpenGenericServicesCanBeResolved
  * ResolvesMixedOpenClosedGenericsAsEnumerable
  * InterfaceConstrainedOpenGenericServicesCanBeResolved
* [ServiceProviderIsServiceSpecificationTests.cs](https://github.com/dotnet/runtime/blob/v6.0.7/src/libraries/Microsoft.Extensions.DependencyInjection.Specification.Tests/src/ServiceProviderIsServiceSpecificationTests.cs)
  * OpenGenericsWithIsService

**Comment by lord-executor** [comment]
@toondedo The latest release v6.1.2 _should_ now work without any workarounds and fully support strongly typed SignalR hubs with `IHubContext<THub, T>`. Please let me know if this works for you or if you run into other issues. Eventually I will add a better SignalR sample to the demo application, but for that I'll need to get a bit deeper into SignalR itself first.

**Comment by toondedo** [comment]
I've had some time to test the v6.1.2. This release works as expected 👍 

Thanks for solving the issue!

**Comment by lord-executor** [comment]
Excellent. And thank you @toondedo for taking the time to create an issue and following-up on it!
